name: Argus
version: '1.0-SNAPSHOT'
main: ca.carleton.sce.argus.Argus
api-version: '1.21.8'

depend: [Citizens, CommandHelper]

libraries:
  - io.github.jason-lang:jason-interpreter:3.2.1

commands:
  spawnagent:
    description: Spawn an Argus agent
    usage: /spawnagent <aslFile> [name]
    permission: argus.spawn
permissions:
  argus.spawn:
    default: op